### ISSUE TITLE
Head should probably generate an error on a directory without a trailing delimiter

### ISSUE THREAD

**Issue by skewballfox** [datafusion-contrib/hdfs-native-object-store#9]
Head should probably generate an error if provided a `url.prefix` that is a valid directory, but doesn't end in a trailing slash. This is to both match the behavior of other object stores, and because [`ListingTableUrl.list_all_files` will just call head](https://github.com/apache/datafusion/blob/4df83f5af42176763da8b10dd93341875544e17a/datafusion/core/src/datasource/listing/url.rs#L216) if it doesn't.

**Comment by Kimahriman** [comment]
I don't think the trailing slash is relevant for the head call, but I agree it does look like head should return an error if called on a directory
